<?php

  function contact_alter_form_alter(&$form, &$form_state, &$form_id) {
    // print '<pre>';
    // print_r($form);
    // print '</pre>';
    // contact_site_form

    if($form_id === 'contact_site_form') {
        $form['copy']['#type'] = 'hidden';
        $form['copy']['#default_value'] = 1;
        $form['subject']['#type'] = 'hidden';
        $form['subject']['#default_value'] = "feedback";
      }
  }
